services:  
  db:
    image: postgres:15-alpine
    env_file: postgres.compose.env
    volumes:
      - db-data:/var/lib/postgresql/data
    
    # Development
    ports:
      - "5432:5432"
  
  api:
    build: ./simple-sales-backend
    env_file: backend.compose.env
    
    # Development
    ports:
      - "8000:8000"

volumes:
  db-data: {}
