services:  
  db:
    image: postgres:15-alpine
    env_file: postgres.compose.env
    volumes:
      - db-data:/var/lib/postgresql/data
    
    # Development
    ports:
      - "5432:5432"

  db-cron:
    build: ./database
    env_file: database.compose.env
    volumes:
      - db-cron-logs:/var/log  # For /var/log/cron.log
    depends_on:
      - db

    command: ["cron"]

  api:
    build: ./backend
    env_file: backend.compose.env
    depends_on:
      - db
    
    # Development
    ports:
      - "8000:8000"

volumes:
  db-data: {}
  db-cron-logs: {}
