services:
  db:
    image: postgres:15-alpine
    env_file: .env.postgres.compose
    volumes:
      - db-data:/var/lib/postgresql/data

    # Development
    ports:
      - "5432:5432"

  db-cron:
    build: ./database
    env_file: .env.database.compose
    command: cron
    volumes:
      - db-cron-logs:/var/log # For /var/log/cron.log
    depends_on:
      - db

  db-migrate:
    build: ./database
    env_file: .env.database.compose
    command: migrate
    depends_on:
      - db

  api:
    build: ./backend
    command: api
    env_file: .env.backend.compose
    depends_on:
      db-migrate:
        condition: service_completed_successfully

    # Development
    ports:
      - "8000:8000"

volumes:
  db-data: {}
  db-cron-logs: {}
